package com.desenrola.repositorios.entidades;

public enum TipoNotificacao {
    NOVA_SOLICITACAO,
    SOLICITACAO_ACEITA,
    SOLICITACAO_RECUSADA,
    ORCAMENTO_RECEBIDO,
    ORCAMENTO_APROVADO,
    ORCAMENTO_RECUSADO,
    PAGAMENTO_CONFIRMADO,
    PAGAMENTO_RECUSADO,
    SERVICO_CONCLUIDO,
    AVALIACAO_RECEBIDA,
    NOVA_MENSAGEM,
    SISTEMA
}
