version: '3.8'

services:
  servidor-mensageria:
    image: rabbitmq:3-management
    container_name: desenrola_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - dados_rabbitmq:/var/lib/rabbitmq

  banco-dados:
    image: mysql:8.0
    container_name: desenrola_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desenrola_db
      MYSQL_USER: desenrola_user
      MYSQL_PASSWORD: desenrola_pass
    volumes:
      - dados_mysql:/var/lib/mysql
      - ./DataBase/desenrola_banco.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  dados_rabbitmq:
  dados_mysql:
